name = "ChadStead"
author = "MrWaffle278"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d373621f3d7f736622bedbc25f274aac672bd402ccbaf4055a1cf43c337011b"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
