name = "ChadStead"
author = "MrWaffle278"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dcc13af16e514c8065df4a3e50b618f54c3fae544f89a83168451014f944a54"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
